Реализовать классы User и Film. Реализовать REST контроллеры классов …
Ersh0w/java-filmorate pull request #1
Opened 2023-03-29 22:54 UTC by Ersh0w

…User и Film.

2023-03-31 20:08 UTC, sergeymamonov requested changes

2023-03-31 20:08 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +        Film film = Film.builder()
В каждом тесте создается филь с валидными полями. Можно сделать метод с аннотацией @BeforeEach, который будет выполняться перед каждым тестом в этом классе. А в самом тесте через сеттер менять валидное поле на невалидное для этого теста.

2023-03-31 20:08 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +public class ValidationException extends Exception {
Если унаследоваться от RuntimeException, то в определении методов, где выбрасывается это исключение, не нужно будет писать  throws ValidationException в определении метода.

2023-03-31 20:08 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film create(@Valid @RequestBody Film film) throws ValidationException {
Можно обойтись без throws ValidationException, изменить класс наследника в исключении.

2023-03-31 20:08 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final LocalDate BIRTHDAY_OF_CINEMA = LocalDate.of(1895, 12, 28);
Смысл переменной, не в том, что это день рождение кино, а в том, что это самая ранняя допустимая дата. Поэтому лучше константе дать соответствующее название

2023-03-31 20:08 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        film.setId(filmIdCounter);
Лучше проще .setId(id);

2023-04-07 12:49 UTC, Ersh0w commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +        Film film = Film.builder()
Исправлено

2023-04-07 12:49 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/exceptions/ValidationException.java
> +public class ValidationException extends Exception {
Исправлено

2023-04-07 12:49 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final LocalDate BIRTHDAY_OF_CINEMA = LocalDate.of(1895, 12, 28);
Исправлено

2023-04-07 12:49 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        film.setId(filmIdCounter);
Исправлено

2023-04-07 20:58 UTC, sergeymamonov approved these changes

2023-04-07 20:58 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +    void idShouldBe1() throws ValidationException {
Исключение не нужно здесь указывать.

2023-04-07 20:59 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final LocalDate BIRTHDAY_OF_CINEMA = LocalDate.of(1895, 12, 28);
Я бы дописал чего именно самая ранняя дата. Но это уже на ваше усмотрение.

2023-04-18 17:01 UTC, Ersh0w commented on src/test/java/ru/yandex/practicum/filmorate/FilmControllerTest.java
> +    void idShouldBe1() throws ValidationException {
Исправлено

2023-04-18 17:01 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Film create(@Valid @RequestBody Film film) throws ValidationException {
Исправлено

2023-04-18 17:11 UTC, merged