Реализовать интерфейсы FilmStorage и UserStorage. Реализовать классы …
Ersh0w/java-filmorate pull request #2
Opened 2023-04-25 09:42 UTC by Ersh0w

…InMemoryFilmStorage и InMemoryUserStorage. Реализовать сервисы UserService и FilmService. Доработать контроллеры.

2023-04-26 11:31 UTC, sergeymamonov requested changes

2023-04-26 11:31 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Можно воспользоваться аннотацией Lombok AllArgsConstruct

2023-04-26 11:31 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          if (film.getReleaseDate().isBefore(EARLIEST_POSSIBLE_FILM_RELEASE_DATE)) {
Валидацию лучше делать в сервисе, не в контроллере.

2023-04-26 11:31 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (filmService.isFilmPresent(film)) {
Лучше всю валидацию перенести в сервис.

2023-04-26 11:31 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(InMemoryFilmStorage filmStorage) {
Можно не писать руками конструктор, а воспользоваться аннотацией Lombok

2023-04-26 11:31 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (film.getId() != null && films.containsKey(film.getId())) {
Можно упростить return film.getId() != null && films.containsKey(film.getId());

2023-04-26 11:31 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (films.containsKey(id)) {
Можно упростить.

2023-04-26 11:31 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (user.getId() != null && users.containsKey(user.getId())) {
Здесь и ниже можно упростить.

2023-04-27 13:04 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService) {
Исправлено

2023-04-27 13:04 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    public FilmService(InMemoryFilmStorage filmStorage) {
Исправлено

2023-04-27 13:09 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (film.getId() != null && films.containsKey(film.getId())) {
Исправлено

2023-04-27 13:09 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +        if (films.containsKey(id)) {
Исправлено

2023-04-27 13:09 UTC, ershovev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        if (user.getId() != null && users.containsKey(user.getId())) {
Исправлено

2023-04-27 16:49 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>          if (film.getReleaseDate().isBefore(EARLIEST_POSSIBLE_FILM_RELEASE_DATE)) {
Исправлено

2023-04-27 16:49 UTC, ershovev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (filmService.isFilmPresent(film)) {
Исправлено

2023-04-28 06:53 UTC, sergeymamonov approved these changes

2023-05-06 12:02 UTC, merged