Add database
Ersh0w/java-filmorate pull request #4
Opened 2023-05-10 05:25 UTC by Ersh0w

Реализовать функционал согласно ТЗ 11. Реализовать классы FilDbStorage, UserDbStorage, MpaDbStorage, GenreDbStorage для работы с базой данных. Для объектов Mpa и Genre реализовать контроллеры и сервисы.

2023-05-11 04:54 UTC, sergeymamonov requested changes

2023-05-11 04:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (!(film.getGenres() == null)) {
Можно проще film.getGenres() != null

2023-05-11 04:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            film.setGenres(new ArrayList<>(10));
Это же дефолтное значение, его можно не ставить.

2023-05-11 04:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (!(film.getGenres() == null)) {
Аналогично.

2023-05-11 04:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (!(film.getGenres() == null)) {
!=

2023-05-11 04:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            jdbcTemplate.update(sqlQuery, film.getId(), genre.getId());
Не очень хорошо делать запросы к БД в цикле. Это большая нагрузка на БД. Затратно по времени из-за передачи по сети.

2023-05-11 04:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        Genre genre = Genre.builder()
Лучше сразу возвращать (без создания промежуточной переменной) return Genre.builder()...

2023-05-11 04:54 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        User user = User.builder()
Посмотрите все места, где можно сразу возвращать результат, то не создавайте лишнюю переменную.

2023-05-11 04:54 UTC, sergeymamonov commented on src/main/resources/data.sql
> +INSERT INTO MPA_RATING (id, name, description)
Зачем так сложно писать. Эта таблица - это словарь. Мы его сами заполняем. В ходе работы приложения эта таблица не правится. Если нужно внести изменения, то разработчик вносит их, поэтому простой INSERT здесь вполне уместен.

2023-05-11 04:54 UTC, sergeymamonov commented on src/main/resources/schema.sql
> +		email VARCHAR NOT NULL,
Размер VARCHAR необходимо ограничивать.

2023-05-11 04:54 UTC, sergeymamonov commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
>          userStorage = new InMemoryUserStorage();
Попробуйте сюда же перенести создание юзера, которое сейчас выполняется в каждом тесте.

2023-05-11 10:39 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (!(film.getGenres() == null)) {
Исправлено

2023-05-11 10:39 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            film.setGenres(new ArrayList<>(10));
Исправлено

2023-05-11 10:40 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (!(film.getGenres() == null)) {
Исправлено

2023-05-11 10:40 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        if (!(film.getGenres() == null)) {
Исправлено

2023-05-11 10:40 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            jdbcTemplate.update(sqlQuery, film.getId(), genre.getId());
Исправлено

2023-05-11 10:40 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        Genre genre = Genre.builder()
Исправлено

2023-05-11 10:40 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        User user = User.builder()
Исправлено

2023-05-11 10:40 UTC, Ersh0w commented on src/main/resources/data.sql
> +INSERT INTO MPA_RATING (id, name, description)
Сергей, просто такая конструкция позволяет создать запись только при ее отсутствии. Нет дублирования при перезапуске приложения. UNIQUE, ON CONFLICT DO NOTHING - ничего из этого не заводится при запуске h2 (крашится при запуске с ошибкой "не удалось выполнить sql скрипт").

2023-05-11 10:41 UTC, Ersh0w commented on src/main/resources/schema.sql
> +		email VARCHAR NOT NULL,
Исправлено

2023-05-11 10:41 UTC, Ersh0w commented on src/test/java/ru/yandex/practicum/filmorate/UserControllerTest.java
>          userStorage = new InMemoryUserStorage();
Исправлено

2023-05-12 05:20 UTC, sergeymamonov requested changes

2023-05-12 05:20 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private List<Genre> getGenresOfFilm(Integer id) {          // получить все жанры фильма
Этот метод делает запросы к БД. При этом этот метод вызывается в циклах. Запросы к БД в цикле - это нехорошо.

2023-05-12 05:23 UTC, sergeymamonov commented on src/main/resources/data.sql
> +INSERT INTO MPA_RATING (id, name, description)
В учебном проекте можно и почистить БД вручную. Не критично конечно оставить так. Но в промышленном коде так писать не нужно) Там решается это с помощью других средств, например liquibase.

2023-05-12 10:20 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    private List<Genre> getGenresOfFilm(Integer id) {          // получить все жанры фильма
Исправлено.

2023-05-13 03:32 UTC, sergeymamonov approved these changes

2023-05-13 03:32 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public FilmDbStorage(JdbcTemplate jdbcTemplate) {
Не обязательно писать конструктор руками, если можно воспользоваться аннотацией Lombok @AllArgsConstructor? Аналогично и для других классов, где можно воспользоваться этой аннотацией

2023-05-14 20:02 UTC, Ersh0w commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +    public FilmDbStorage(JdbcTemplate jdbcTemplate) {
Исправлено.

2023-05-14 20:04 UTC, merged